services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}    
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  redis-data: