services:
  mongo-db:
    image: mongo
    restart: always    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./docker-volumes/mongo-${COMPOSE_PROJECT_NAME}:/data/db
    ports:
      - ${MONGO_PORT}:27017

  redis:
    image: redis:latest    
    restart: always
    ports:
    - ${REDIS_PORT}:6379
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}    
    volumes:
      - ./docker-volumes/redis-${COMPOSE_PROJECT_NAME}:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]