services:
  mongo-db:
    image: mongo:7.0.20
    restart: always    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./docker-volumes/mongo-${NODE_ENV}:/data/db
    ports:
      - ${MONGO_PORT}:27017

  redis:
    image: redis:8.0.1       
    restart: always
    ports:
    - ${REDIS_PORT}:6379
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}    
    volumes:
      - ./docker-volumes/redis-${NODE_ENV}:/data
      - ./redis/conf:/usr/local/etc/redis
    command: 
      - redis-server
      - /usr/local/etc/redis/redis.conf 
      - --requirepass
      - ${REDIS_PASSWORD}