import { HydratedDocument, Model, Types } from "mongoose";
import { CreateUserValidator, LoginUserValidator, UpdateUserValidator } from "@root/rules/validators/models/user";
import { EmailService, HashingService, JwtBlackListService, JwtService, LoggerService, SystemLoggerService, ConfigService } from ".";
import { FORBIDDEN_MESSAGE } from "@root/rules/errors/messages/error.messages";
import { HttpError } from "../rules/errors/http.error";
import { ITasks, IUser, UserFromRequest } from "@root/interfaces";
import { TOKEN_PURPOSES } from "@root/rules/constants";
import { UserRole } from "@root/types/user/user-roles.type";
import { handleDbDuplicatedKeyError } from "@logic/errors/database";

export class UserService {

    constructor(
        private readonly configService: ConfigService,
        private readonly userModel: Model<IUser>,
        private readonly tasksModel: Model<ITasks>,
        private readonly hashingService: HashingService,
        private readonly jwtService: JwtService,
        private readonly jwtBlacklistService: JwtBlackListService,
        private readonly loggerService: LoggerService,
        private readonly emailService: EmailService,
    ) {}

    // returns the user to modify in order to not have to findOne it again
    private async getTargetUserIfAuthorized(requestUserInfo: { id: string, role: UserRole }, userIdToUpdate: string): Promise<HydratedDocument<IUser> | null> {
        const userToModify = await this.findOne(userIdToUpdate);
        // admin users can modify other users (but not other admins)
        if (requestUserInfo.role === 'admin' && userToModify.role !== 'admin')
            return userToModify;
        // users can modify themselves
        if (requestUserInfo.id === userToModify.id)
            return userToModify;
        return null;
    }

    private async blackListToken(jti: string, tokenExp: number) {
        const currentTime = Math.floor(Date.now() / 1000);
        const remainingTokenTTL = tokenExp! - currentTime;
        this.loggerService.debug(`Token ${jti} blacklisted`);
        await this.jwtBlacklistService.blacklist(jti, remainingTokenTTL);
    }

    private generateSessionToken(userId: string): string {
        const expTime = this.configService.JWT_SESSION_EXP_TIME;
        const token = this.jwtService.generate(expTime, {
            id: userId,
            purpose: TOKEN_PURPOSES.SESSION
        });
        this.loggerService.info(`Session token generated, expires at ${expTime}`);
        return token;
    }

    private async sendEmailValidationLink(email: string): Promise<void> {
        const jwtExpTime = this.configService.JWT_EMAIL_VALIDATION_EXP_TIME;
        const token = this.jwtService.generate(jwtExpTime, {
            purpose: TOKEN_PURPOSES.EMAIL_VALIDATION,
            email
        });
        // web url is appended with a default "/" when read
        const link = `${this.configService.WEB_URL}api/users/confirmEmailValidation/${token}`;
        await this.emailService.sendMail({
            to: email,
            subject: 'Email validation',
            html: `
            <h1> Validate your email </h1>
            <p> Click below to validate your email </p>
            <a href= "${link}"> Validate your email ${email} </a>`,
        });
        this.loggerService.info(`Email validation sent to ${email}`);
    }

    private async consumeEmailValidationToken(token: string): Promise<string> {
        // token was generated by this server
        const payload = this.jwtService.verify<{ email: string }>(token);
        if (!payload) {
            this.loggerService.error('Invalid token, not generated by this server');
            throw HttpError.badRequest('Invalid token');
        }
        // email must be in token
        const emailInToken = payload.email;
        if (!emailInToken) {
            this.loggerService.error('Email not in token');
            throw HttpError.badRequest('Invalid token');
        }
        // correct purpose
        const validPurpose = payload.purpose === TOKEN_PURPOSES.EMAIL_VALIDATION;
        if (!validPurpose) {
            this.loggerService.error('Unexpected token purpose');
            throw HttpError.badRequest('Invalid token');
        }
        // token is not blacklisted
        const tokenIsBlacklisted = await this.jwtBlacklistService.isBlacklisted(payload.jti)
        if (tokenIsBlacklisted) {
            this.loggerService.error('Token is blacklisted');
            throw HttpError.badRequest('Invalid token');
        }
        // single-use token
        await this.blackListToken(payload.jti, payload.exp!);
        return payload.email;
    }

    async requestEmailValidation(id: string): Promise<void> {
        const user = await this.userModel.findById(id).exec();
        if (!user) {
            this.loggerService.error(`User with id ${id} not found`);
            throw HttpError.badRequest('User not found');
        }
        // email cannot be validated twice
        if (user.emailValidated === true) {
            this.loggerService.error(`Email ${user.email} is already validated`);
            throw HttpError.badRequest('User email is already validated');
        }
        await this.sendEmailValidationLink(user.email);
    }

    async confirmEmailValidation(token: string): Promise<void> {
        const emailInToken = await this.consumeEmailValidationToken(token);

        // check user existence
        const user = await this.userModel.findOne({ email: emailInToken }).exec();
        if (!user) {
            this.loggerService.error(`User ${emailInToken} not found`);
            throw HttpError.notFound('User not found');
        }

        // update 
        user.emailValidated = true;
        user.role = 'editor';
        await user.save();
        this.loggerService.info(`User ${user.id} email validated`);
    }

    async create(user: CreateUserValidator): Promise<{ user: HydratedDocument<IUser>, token: string }> {
        try {
            // hashing
            const passwordHash = await this.hashingService.hash(user.password);
            user.password = passwordHash;

            // creation in db
            const created = await this.userModel.create(user);

            // token generation
            const token = this.generateSessionToken(created.id);

            this.loggerService.info(`User ${created.id} created`);
            return {
                user: created,
                token,
            };

        } catch (error: any) {
            if (error.code === 11000)
                handleDbDuplicatedKeyError(error, this.loggerService);
            throw error;
        }
    }

    async login(userToLogin: LoginUserValidator): Promise<{ user: HydratedDocument<IUser>, token: string }> {
        // check user existence
        const userDb = await this.userModel
            .findOne({ email: userToLogin.email })
            .exec();

        if (!userDb) {
            this.loggerService.error(`User ${userToLogin.email} not found`);
            throw HttpError.badRequest(`User with email ${userToLogin.email} not found`);
        }

        // check password
        const passwordOk = await this.hashingService.compare(
            userToLogin.password,
            userDb.password
        );

        if (!passwordOk) {
            this.loggerService.error('Password does not match');
            throw HttpError.badRequest('Email or password is not correct');
        }

        // token generation
        const token = this.generateSessionToken(userDb.id);

        this.loggerService.info(`User ${userDb.id} logged in`);
        return {
            user: userDb,
            token,
        };
    }

    async logout(requestUserInfo: UserFromRequest): Promise<void> {
        await this.blackListToken(requestUserInfo.jti, requestUserInfo.tokenExp);
        this.loggerService.info(`User ${requestUserInfo.id} logged out`);
    }

    async findOne(id: string): Promise<HydratedDocument<IUser>> {
        let userDb;

        if (Types.ObjectId.isValid(id))
            userDb = await this.userModel.findById(id).exec();

        // id is not valid / user not found
        if (!userDb) {
            this.loggerService.error(`User ${id} not found`)
            throw HttpError.notFound(`User with id ${id} not found`);
        }

        return userDb;
    }

    async findAll(limit: number, page: number): Promise<HydratedDocument<IUser>[]> {
        if (limit <= 0) {
            throw HttpError.badRequest('Limit must be a valid number');
        }

        if (limit > 100) {
            throw HttpError.badRequest('Limit is too large');
        }

        const totalDocuments = await this.userModel
            .countDocuments()
            .exec();

        if (totalDocuments === 0) {
            return [];
        }

        const totalPages = Math.ceil(totalDocuments / limit);

        if (page <= 0) {
            throw HttpError.badRequest('Page must be a valid number');
        }

        if (page > totalPages) {
            throw HttpError.badRequest('Invalid page');
        }

        const offset = (page - 1) * limit;

        return await this.userModel
            .find()
            .skip(offset)
            .limit(limit)
            .sort({ name: 'asc' })
            .exec();
    }

    async deleteOne(requestUserInfo: { id: string, role: UserRole }, id: string): Promise<void> {
        const userToDelete = await this.getTargetUserIfAuthorized(requestUserInfo, id);

        if (!userToDelete) {
            this.loggerService.error(`Not authorized to perform this action`);
            throw HttpError.forbidden(FORBIDDEN_MESSAGE);
        }

        await userToDelete.deleteOne().exec();
        this.loggerService.info(`User ${id} deleted`);

        // remove all tasks associated
        const tasksRemoved = await this.tasksModel.deleteMany({ user: userToDelete.id });
        this.loggerService.info(`${tasksRemoved.deletedCount} tasks associated to user removed`);
    }

    async updateOne(requestUserInfo: { id: string, role: UserRole }, id: string, propertiesUpdated: UpdateUserValidator): Promise<HydratedDocument<IUser>> {
        try {
            const userToUpdate = await this.getTargetUserIfAuthorized(requestUserInfo, id);
            if (!userToUpdate) {
                this.loggerService.error(`Not authorized to perform this action`);
                throw HttpError.forbidden(FORBIDDEN_MESSAGE);
            }

            if (propertiesUpdated.password) {
                userToUpdate.password = await this.hashingService.hash(propertiesUpdated.password);
            }

            // if email is different change "emailValidated" prop        
            if (propertiesUpdated.email) {
                if (userToUpdate.email !== propertiesUpdated.email && requestUserInfo.role != 'admin') {
                    userToUpdate.emailValidated = false;
                    userToUpdate.role = 'readonly';
                }
                userToUpdate.email = propertiesUpdated.email;
            }

            if (propertiesUpdated.name) {
                userToUpdate.name = propertiesUpdated.name
            }

            await userToUpdate.save();
            this.loggerService.info(`User ${id} updated`);

            return userToUpdate;
        } catch (error: any) {
            if (error.code === 11000)
                handleDbDuplicatedKeyError(error, this.loggerService);
            throw error;
        }
    }
}