import { Express } from 'express';
import { TasksDataGenerator } from 'src/generators/tasks.generator';
import { UserDataGenerator } from 'src/generators/user.generator';
import { ModelLoader } from 'src/models/model.loader';
import { ConfigService } from 'src/services/config.service';
import { HashingService } from 'src/services/hashing.service';
import { LoggerService } from 'src/services/logger.service';
import { PasswordRecoveryTokenService } from 'src/services/password-recovery-token.service';
import { RedisService } from 'src/services/redis.service';
import { RefreshTokenService } from 'src/services/refresh-token.service';
import { TestAgent } from './test-agent.interface';
import { JwtBlackListService } from 'src/services/jwt-blacklist.service';
import { EmailValidationTokenService } from 'src/services/email-validation-token.service';
import { JwtService } from 'src/services/jwt.service';
import { SessionTokenService } from 'src/services/session-token.service';
import { CacheService } from 'src/services/cache.service';
import { TaskResponse } from 'src/types/tasks/task-response.type';

export interface ITestKit {
    configService: ConfigService;
    redisService: RedisService;
    models: ModelLoader;
    userData: UserDataGenerator;
    taskData: TasksDataGenerator;
    tasksCacheService: CacheService<TaskResponse>;
    loggerServiceMock: LoggerService;
    refreshJwt: JwtService;
    sessionJwt: JwtService;
    jwtBlacklistService: JwtBlackListService;
    hashingService: HashingService;
    refreshTokenService: RefreshTokenService;
    passwordRecoveryTokenService: PasswordRecoveryTokenService;
    sessionTokenService: SessionTokenService;
    emailValidationTokenService: EmailValidationTokenService;
    server: Express;
    agent: TestAgent;
    urls: {
        seedUsers: string;
        seedTasks: string;
        usersAPI: string;
        myProfile: string;
        register: string;
        login: string;
        logout: string;
        logoutAll: string;
        requestEmailValidation: string;
        confirmEmailValidation: string;
        resetPassword: string;
        forgotPassword: string;
        tasksAPI: string;
        createTask: string;
        findAllTasksByUser: string;
        refreshToken: string;
        health: string;
    };
}
